# Gigantic 設定ファイル
# このファイルを削除orリネームしてからサーバを起動するとデフォルトの設定ファイルが再生成されます(エラーが出たときは真っ先に試しましょう)

# サーバ識別設定
# 複数サーバ構成にする場合はこの値をサーバごとに変更します
servernum: 1

# MySQLデータベースへの接続設定
# xamppの設定を変えていなければデフォルトの値で問題ありません
host: 'localhost'
port: '3306'
db: 'gigantic'
id: 'root'
pw: ''

# 引き継ぎ用データベースへの接続設定
# 無ければnoに設定する
olddatabase : yes
# SeichiAssistデータベース
seichiassist:
  host: 'localhost'
  port: '3306'
  db: 'seichiassist'
  id: 'root'
  pw: ''

#データロードの最大試行回数
maxattempt : 5


# 機能：MineBoost設定
# numofpeople:接続人数による増加
# minutemine:1分間の整地量による増加
#
#
#
mineboost:
  rate:
    numofpeople: 0.5
    minutemine: 0.01

# 整地レベル設定
# レベルアップできる最大値
maxseichilevel: 500
# レベルが考慮される最大値
considerableseichilevel: 300

# 機能：整地レベルメッセージ設定
# levelupmessage:レベルアップの度に表示
# levelmessage:特定のレベルに上がると表示(1は指定できません）

#初回ログイン時のメッセージ
firstjoinmessage : "整地鯖では整地をするとレベルが上がり、様々な恩恵が受けられます。\n初めての方は整地ワールドで掘ってレベルを上げてみましょう！\n木の棒を右クリックしてメニューを開き右上のビーコンボタンをクリック！"

seichi:
  levelupmessage: '&6整地レベルが%gp_seichilevel%になりました．'
  levelmessage:
    2: "&eアイテムがドロップしないですか？\nそれは，MineStackと呼ばれる機能で自動的にスタックされているためです．\n木の棒メニューからMineStackを選択してアイテムを取り出しましょう！"
    3: "&eやけに早く掘れる気がする…？\n整地鯖では接続人数や採掘量に応じて採掘速度にブーストが掛かります。"
    4: "&e整地鯖では死んでもロストしません。\n気軽に冒険、整地してくださいね。\nそういえば当鯖の「ルール」もう確認しましたか？\n手遅れになる前に確認しておきましょうネ。\n木の棒メニューからどうぞ。"
    5: "&eDynmapでどこに誰がいるのか、何があるのかなどを見ることができます。\nURLはこちら→http://seichi.click/d/DynmapLinks"
    6: "&e整地鯖ではホームポイントを作成して，その場所までワープすることができます．\n詳しくは，木の棒メニューをご覧ください．"
    7: "&e整地鯖をもっと良くするために、\n是非JPMCSに投票をお願いします。\n1日1回投票出来ます。投票すると様々な特典を受け取れます！\nURLはこちら→https://minecraft.jp/servers/54d3529e4ddda180780041a7/vote"
    8: "&eもしかして，ガチャ券を手に入れましたか？ガチャ券を右クリックすると豪華景品があたるかも？"
    9: "&eレベル10になると，この鯖の醍醐味でもある\n範囲破壊スキルが習得できます！\nあともう少し，ファイト！！"
    10: "&e初めてのアクティブスキル【エクスプロージョン】を習得できます！\n習得するには木の棒メニューのアクティブスキルブックをクリック！"
    12: "&eスキルには慣れましたか？\nマナを回復したい時は，ピッケルをもってFキーで\nスキルを解除してから掘ってください！\nパッシブスキル【マナリカバリー】が発動します！"
    14: "&eそろそろ家を建てましょう！\n自分の家はメインワールドで建てることができます。\n他人の保護の無い所に保護を設定してから建てましょう。\n保護方法は公式wikiに詳しい説明があります。木の棒メニューからどうぞ。\n自分のチェストは設定した保護内に置けば自動でロックされます。"
    18: "&e建築の時など、MineBoostが邪魔な時は\n木の棒メニューのパッシブスキルブックからONとOFFを変更できます。"
    22: "&eアクティブスキルの範囲設定が難しい！\nという方は自動化をお勧めします．\n木の棒メニューの各種設定からどうぞ"
    28: "&eツールポーチに整地で使用するツールを入れておくと，\n手に持っているツールが壊れる前に自動で装填してくれます"
    34: "&e実績を解除すると二つ名パーツを手に入れることが出来ます！\nこのパーツを組み合わせて自分だけの二つ名を作りましょう！\n棒メニューからどうぞ！"
    42: "&e討伐したMOBに応じて狩猟ポイントを手に入れることが出来ます！\nこのポイントを使ってレアアイテムを手に入れましょう！\n棒メニューからどうぞ！"
    46: "&e放置するなら放置釣りをしましょう！\n放置しながらおさかなを採ったり，釣りポイントをためてアイテムを購入することができます！\n棒メニューからどうぞ！"
    48: "&e整地鯖のDiscordはご存知でしょうか．\n整地鯖の仲間と共にお家を作ったり，整地したりすると，もっと楽しいですよ！\nURLはこちら→http://seichi.click/d/Discord"
    50: "&e遠距離スキル【マジックドライブ】はピッケルを持ちながら\n遠くのブロックを右クリックすると一定時間経過後，範囲破壊することができます！\n【エクスプロージョン】と併用できますので，うまく使ってみてください！"
    60: "&eパッシブスキル【セキュアブレイク】は全てのアクティブスキルで\n破壊されるブロックの周りの液体を凝固してくれるスキルです！\n棒メニューからオンオフできます！"
    100: "&e凝固スキル【コンデンセーション】は発動中，\n一定間隔で周囲の液体を凝固させてくれるスキルです！\nこれでようやく君も海を攻略できる！"
    150: "&e周囲破壊スキル【ルインフィールド】は発動中，\n一定間隔で周囲のブロックを破壊するスキルです！\n４つのアクティブスキルを上手に使いこなして，整地ランキング上位を目指しましょう！！"
    170: "&eパッシブスキル【スカイウォーク】は発動中，\nプレイヤーの足場を生成し，落下から守ってくれます！\n"
    250: "&e最後のアクティブスキル【フェアリーエイジス】は\n破壊系スキルを使用時に破壊範囲の上方を追加破壊してくれるスキルです！\n妖精さんの破壊ペースは変わりませんので，気ままに整地しましょう！"
    300: "&eここまできてしまったのですね...\nチュートリアルが終了しました．\nここから先は未知の世界です．思うがままに整地してください．\n\n\nそれでは...君に幸あれ．"
    500: "&e...\n...\n...\n...\n...\nお疲れ様です．\nここまで楽しんでくださってありがとうございます．\nもう，整地しなくていいんですよ．\nさぁ，手を止めて．新しいMinecraftIDを購入したら，また会いましょう...\n...\n...\n...Fin"

#Fly時の1分当たりの経験値消費量
flyexp: 50

# 建築レベル設定
# レベルアップできる最大値
maxbuildlevel: 100

#ブロック設置カウントの1分上限
BuildNum1minLimit: 100

#MineStackブロック一括クラフト・必要経験値量
minestack_BlockCraft:
  level1: 25
  level2: 35
  level3: 45

#範囲設置スキル
ZoneSetSkill:
  level: 15
  minestack: 30

#ブロックを並べるスキル
BlockLineUpSkill:
  level: 15
  minestack: 30

#設置ブロック変換スキル
ConvertPlacementSkill:
  level: 50

#ブロック着色スキル
BlockColoringSkill:
  level: 25

#ブロック洗浄スキル
BlockWashingSkill:
  level: 30

#スキルを使ってブロックを並べたときの建築量上昇倍率
BlockCountMag: 0.2

#スキルの使えるワールド
skillworld:
  - world_SW
  - world_SW_2
  - world_SW_nether
  - world_SW_the_end
  - world_SW_zero

#整地経験値が2倍になるワールド
bonusworld:
  - world_SW_zero

#重力値設定
#通常破壊時に許容する高さ
generalgravityheight: 10

#パッシブスキル設定
#セキュアブレイクが解放されるレベル
securebreakunlocklevel: 60

#スカイウォークスキル関連
skywalk:
  Unlocklevel: 170
  Mana: 100
  #足場ブロック消失時間(単位:秒)あまり短くしすぎると、鯖負荷が増大するかも
  BreakSec: 2

# ホームポイント数の設定
subhomemax: 5

#ガチャ関連の設定
Gacha:
  maxSize: 300
